import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Function to generate file IDs with configurable folder and prefix
function generateStudyIds(folder: string, prefix: string, start: number, end: number): string[] {
  const ids: string[] = [];
  for (let i = start; i <= end; i++) {
    const idStr = i.toString().padStart(3, '0');
    ids.push(`${folder}/${prefix}_study_${idStr}`);
  }
  return ids;
}

function generateSidebarItems(folder: string, prefix: string, modules: { title?: string; start: number; end: number }[]) {
  return modules.flatMap(mod => {
    const items = generateStudyIds(folder, prefix, mod.start, mod.end);

    // If title is provided, create a Category (Folder)
    if (mod.title) {
      return [{
        type: 'category' as const,
        label: mod.title,
        items: items,
      }];
    }

    // If no title, expand as Flat Docs (No Folder)
    return items.map(id => ({
      type: 'doc' as const,
      id: id,
    }));
  });
}



const dddModules = [
  { title: "第1部：【そもそも設計とは何か？】なぜコードを書く前に考えるのか", start: 1, end: 10 },
  { title: "第2部：【DDDの大きな枠組み】万能ではない「道具」の使い所", start: 11, end: 20 },
  { title: "第3部：【戦略的設計】AIに「このアプリの正解」を教える", start: 21, end: 35 },
  { title: "第4部：【設計の基礎力：戦術】AIを暴走させない「型」の作り方", start: 36, end: 55 },
  { title: "第5部：【アーキテクチャ】1人のスピードを最大化する構造", start: 56, end: 75 },
  { title: "第6部：【DDD以外の選択肢と割り切り】現実的な設計者へ", start: 76, end: 90 },
  { title: "第7部：【継続と成長】AI時代に生き残る設計者になる", start: 91, end: 100 },
];

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {


  dryCsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dry_cs',
    },
  ],
  dryTsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dry_ts',
    },
  ],

  dddCsSidebar: [
    {
      type: 'doc',
      id: 'ddd_cs/ddd_cs_index',
    },
    ...generateSidebarItems('ddd_cs', 'ddd_cs', dddModules),
  ],
  adrCsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'adr_cs',
    },
  ],
  adrTsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'adr_ts',
    },
  ],
  yagniCsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'yagni_cs',
    },
  ],
  yagniTsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'yagni_ts',
    },
  ],
  kissCsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'kiss_cs',
    },
  ],
  kissTsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'kiss_ts',
    },
  ],
  solidCsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'solid_cs',
    },
  ],
  solidTsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'solid_ts',
    },
  ],
  socCsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'soc_cs',
    },
  ],
  socTsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'soc_ts',
    },
  ],
  hcLcCsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'hc_lc_cs',
    },
  ],
  hcLcTsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'hc_lc_ts',
    },
  ],
};

export default sidebars;
